const test = require("node:test");
const assert = require("node:assert/strict");
const CallSlot = require("../../models/CallSlot");
const { zonedDateTimeToUtc, buildCanonicalSlotFields, formatDateInZone, addCalendarDays, bookingWindowEnd, validateTimezone, formatSlotDisplay } = require("../../utils/slotTime");
const {
  buildSlotOperations,
  buildOutsideHorizonCleanupQuery,
  startSlotMaintenance,
  stopSlotMaintenance,
} = require("../../services/slotMaintenanceService");
const { deterministicMessageId, sanitizePayload } = require("../../services/outboxService");
const { getBackoffMs, isPermanentError } = require("../../services/outboxWorker");
const { EMAIL_TEMPLATE_TYPES, renderEmailTemplate } = require("../../utils/emailTemplates");

test("Cairo wall-clock slots round-trip through UTC", () => {
  const utc = zonedDateTimeToUtc("2026-08-05", "16:00", "Africa/Cairo");
  assert.ok(utc instanceof Date);
  assert.equal(formatDateInZone(utc, "Africa/Cairo"), "2026-08-05");
  assert.equal(addCalendarDays("2026-12-31", 1), "2027-01-01");
  assert.equal(validateTimezone("Africa/Cairo"), true);
  assert.equal(validateTimezone("Mars/Olympus"), false);
});

test("canonical slot fields keep legacy display values and authoritative Cairo timestamps together", () => {
  const fields = buildCanonicalSlotFields({
    date: "2026-08-05", startTime: "16:00", endTime: "17:00", timezone: "Africa/Cairo",
  });
  assert.deepEqual(
    { date: fields.date, startTime: fields.startTime, endTime: fields.endTime, timezone: fields.timezone },
    { date: "2026-08-05", startTime: "16:00", endTime: "17:00", timezone: "Africa/Cairo" }
  );
  assert.equal(fields.startsAt.toISOString(), "2026-08-05T13:00:00.000Z");
  assert.equal(fields.endsAt.toISOString(), "2026-08-05T14:00:00.000Z");
  assert.throws(() => buildCanonicalSlotFields({ date: "2026-02-30", startTime: "16:00", endTime: "17:00" }), /valid YYYY-MM-DD/);
  assert.throws(() => buildCanonicalSlotFields({ date: "2026-08-05", startTime: "17:00", endTime: "16:00" }), /after start/);
});

test("automatic horizon operations always contain canonical timestamps and runtime model creation rejects missing timestamps", async () => {
  const previous = { timezone: process.env.BUSINESS_TIMEZONE, days: process.env.BOOKING_WINDOW_DAYS };
  process.env.BUSINESS_TIMEZONE = "Africa/Cairo";
  process.env.BOOKING_WINDOW_DAYS = "7";
  const operations = buildSlotOperations(new Date("2026-08-05T12:00:00.000Z"));
  assert.ok(operations.length > 0 && operations.length <= 49);
  for (const operation of operations) {
    const fields = operation.updateOne.update.$setOnInsert;
    assert.ok(fields.startsAt instanceof Date);
    assert.ok(fields.endsAt instanceof Date);
    assert.ok(fields.endsAt > fields.startsAt);
    assert.equal(fields.timezone, "Africa/Cairo");
    assert.equal(fields.source, "auto");
    assert.equal(fields.isAutoGenerated, true);
  }
  const invalid = new CallSlot({ date: "2026-08-05", startTime: "16:00", endTime: "17:00" });
  await assert.rejects(invalid.validate(), /authoritative startsAt and endsAt/);
  if (previous.timezone === undefined) delete process.env.BUSINESS_TIMEZONE; else process.env.BUSINESS_TIMEZONE = previous.timezone;
  if (previous.days === undefined) delete process.env.BOOKING_WINDOW_DAYS; else process.env.BOOKING_WINDOW_DAYS = previous.days;
});

test("automatic maintenance is opt-in in development and tests and logs explicit startup", async () => {
  const previous = { nodeEnv: process.env.NODE_ENV, enabled: process.env.SLOT_MAINTENANCE_ENABLED };
  const logs = [];
  let runs = 0;
  let schedules = 0;
  const options = {
    runMaintenance: async ({ trigger }) => { runs += 1; return { trigger, slotsEnsured: 0, expiredSlotsCleaned: 0, outsideHorizonSlotsCleaned: 0 }; },
    setIntervalFn: () => { schedules += 1; return { unref() {} }; },
    logFn: (level, event, fields) => logs.push({ level, event, fields }),
  };

  stopSlotMaintenance();
  process.env.NODE_ENV = "development";
  process.env.SLOT_MAINTENANCE_ENABLED = "false";
  assert.equal(startSlotMaintenance(options), false);
  assert.equal(runs, 0);
  assert.equal(schedules, 0);

  process.env.NODE_ENV = "test";
  delete process.env.SLOT_MAINTENANCE_ENABLED;
  assert.equal(startSlotMaintenance(options), false);
  assert.equal(runs, 0);

  process.env.NODE_ENV = "production";
  process.env.SLOT_MAINTENANCE_ENABLED = "true";
  assert.equal(startSlotMaintenance(options), true);
  await new Promise((resolve) => setImmediate(resolve));
  assert.equal(runs, 1);
  assert.equal(schedules, 1);
  assert.ok(logs.some((entry) => entry.event === "slot_maintenance_disabled"));
  assert.ok(logs.some((entry) => entry.event === "slot_maintenance_started"));
  assert.ok(logs.some((entry) => entry.event === "slot_maintenance_completed" && entry.fields.trigger === "automatic"));
  stopSlotMaintenance();
  if (previous.nodeEnv === undefined) delete process.env.NODE_ENV; else process.env.NODE_ENV = previous.nodeEnv;
  if (previous.enabled === undefined) delete process.env.SLOT_MAINTENANCE_ENABLED; else process.env.SLOT_MAINTENANCE_ENABLED = previous.enabled;
});

test("booking horizon ends on the seventh Cairo calendar day", () => {
  process.env.BOOKING_WINDOW_DAYS = "7";
  const end = bookingWindowEnd(new Date("2026-08-05T12:00:00Z"), "Africa/Cairo");
  assert.equal(formatDateInZone(end, "Africa/Cairo"), "2026-08-11");
});

test("slot display uses authoritative timestamps and a friendly Cairo range", () => {
  process.env.BUSINESS_TIMEZONE = "Africa/Cairo";
  const display = formatSlotDisplay({
    startsAt: new Date("2026-08-10T13:00:00.000Z"),
    endsAt: new Date("2026-08-10T14:00:00.000Z"),
    timezone: "Africa/Cairo",
  });

  assert.equal(display, "Monday, August 10 · 4:00 PM–5:00 PM (Cairo time)");
  assert.doesNotMatch(display, /16:00|Africa\/Cairo|2026-08-10/);
});

test("outside-horizon cleanup begins strictly after the Cairo booking window and excludes manual slots", () => {
  const now = new Date("2026-08-05T12:00:00Z");
  const query = buildOutsideHorizonCleanupQuery(now);
  assert.equal(query.startsAt.$gt.toISOString(), bookingWindowEnd(now, "Africa/Cairo").toISOString());
  assert.equal(query.isAutoGenerated, true);
  assert.deepEqual(query.source, { $ne: "manual" });
  assert.equal(query.isBooked, false);
  assert.equal(query.bookedBy, null);
  assert.deepEqual(query.protectedFromCleanup, { $ne: true });
  assert.deepEqual(query.$expr, { $gt: ["$endsAt", "$startsAt"] });
});

test("outbox retry policy is bounded and permanent failures are classified", () => {
  const first = getBackoffMs(1);
  const late = getBackoffMs(20);
  assert.ok(first >= 60000 && first < 72000);
  assert.ok(late >= 21600000 && late < 25920000);
  assert.equal(isPermanentError({ responseCode: 550 }), true);
  assert.equal(isPermanentError({ code: "ETIMEDOUT" }), false);
  assert.equal(deterministicMessageId("same-event"), deterministicMessageId("same-event"));
});

test("outbox payload sanitization removes Mongo-style keys", () => {
  assert.deepEqual(sanitizePayload({ safe: "yes", $where: "bad", "a.b": "bad" }), { safe: "yes" });
});

test("email templates escape stored customer content", () => {
  process.env.CLIENT_URL = "https://www.example.com";
  const rendered = renderEmailTemplate("review.owner", { name: "<script>alert(1)</script>", rows: [{ label: "Review", value: "<img src=x>" }] });
  assert.doesNotMatch(rendered.html, /<script>alert/);
  assert.doesNotMatch(rendered.html, /<img src=x>/);
  assert.match(rendered.html, /&lt;img src=x&gt;/);
});

test("all transactional templates render compact HTML, text, and website CTAs", () => {
  process.env.CLIENT_URL = "https://www.web-district.com";
  const payload = {
    name: "Client Name",
    businessName: "Studio Name",
    email: "client@example.com",
    status: "Accepted",
    token: "a".repeat(64),
    ctaPath: `/reset-password/${"b".repeat(64)}`,
    title: "Project update",
    intro: "A concise project update.",
    subject: "Web District project update",
    rows: [{ label: "Slot", value: "Monday, August 10 · 4:00 PM–5:00 PM (Cairo time)" }],
  };

  for (const template of EMAIL_TEMPLATE_TYPES) {
    const rendered = renderEmailTemplate(template, payload);
    assert.ok(rendered.subject);
    assert.ok(rendered.text);
    assert.ok(rendered.html);
    assert.match(rendered.html, /display:none;max-height:0/);
    assert.doesNotMatch(rendered.html, /\b(?:undefined|null)\b/);
    assert.doesNotMatch(rendered.text, /\b(?:undefined|null)\b/);
    assert.doesNotMatch(rendered.html, /api\.web-district\.com|onrender\.com|localhost|127\.0\.0\.1/i);
    assert.doesNotMatch(rendered.html, /background:#050505[^>]+color:#050505/i);
    assert.match(rendered.html, /color:#F7F2EC;-webkit-text-fill-color:#F7F2EC/);
    assert.match(rendered.text, /https:\/\/www\.web-district\.com\//);
  }
});
