const mongoose = require("mongoose");

const callSlotSchema = new mongoose.Schema(
  {
    date: {
      type: String,
      required: [true, "Date is required"],
    },

    startTime: {
      type: String,
      required: [true, "Start time is required"],
    },

    endTime: {
      type: String,
      required: [true, "End time is required"],
    },
    startsAt: { type: Date, default: null },
    endsAt: { type: Date, default: null },
    timezone: { type: String, default: "Africa/Cairo", maxlength: 80 },
    source: { type: String, enum: ["auto", "manual", "legacy"], default: "manual" },

    isBooked: {
      type: Boolean,
      default: false,
    },
    bookedBy: { type: mongoose.Schema.Types.ObjectId, ref: "Appointment", default: null },

    isActive: {
      type: Boolean,
      default: true,
    },

    notes: {
      type: String,
      default: "",
    },

    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    protectedFromCleanup: { type: Boolean, default: false },
  },
  {
    timestamps: true,
    strict: "throw",
  }
);

callSlotSchema.index(
  {
    date: 1,
    startTime: 1,
    endTime: 1,
  },
  {
    unique: true,
    name: "unique_active_call_slot_time",
    partialFilterExpression: { isActive: true },
  }
);

callSlotSchema.index({ startsAt: 1, isActive: 1, isBooked: 1 }, { name: "upcoming_slot_availability" });
callSlotSchema.index({ endsAt: 1, isBooked: 1, protectedFromCleanup: 1 }, { name: "expired_slot_cleanup" });

const CallSlot = mongoose.model("CallSlot", callSlotSchema);

module.exports = CallSlot;
