const mongoose = require("mongoose");

const callSlotSchema = new mongoose.Schema(
  {
    date: {
      type: String,
      required: [true, "Date is required"],
    },

    startTime: {
      type: String,
      required: [true, "Start time is required"],
    },

    endTime: {
      type: String,
      required: [true, "End time is required"],
    },

    isBooked: {
      type: Boolean,
      default: false,
    },

    isActive: {
      type: Boolean,
      default: true,
    },

    notes: {
      type: String,
      default: "",
    },

    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

callSlotSchema.index(
  {
    date: 1,
    startTime: 1,
    endTime: 1,
  },
  {
    unique: true,
    name: "unique_call_slot_time",
  }
);

const CallSlot = mongoose.model("CallSlot", callSlotSchema);

module.exports = CallSlot;
