const crypto = require("crypto");
const CallSlot = require("../models/CallSlot");
const Appointment = require("../models/Appointment");
const MaintenanceLock = require("../models/MaintenanceLock");
const { getBusinessTimezone, getBookingWindowDays, formatDateInZone, addCalendarDays, zonedDateTimeToUtc } = require("../utils/slotTime");

const LOCK_NAME = "slot-maintenance";
const owner = `${process.pid}:${crypto.randomUUID()}`;
let timer = null;
let running = false;

const buildSlotOperations = (now = new Date()) => {
  const timezone = getBusinessTimezone();
  const today = formatDateInZone(now, timezone);
  const operations = [];
  for (let dayOffset = 0; dayOffset < getBookingWindowDays(); dayOffset += 1) {
    const date = addCalendarDays(today, dayOffset);
    for (let hour = 16; hour < 23; hour += 1) {
      const startTime = `${String(hour).padStart(2, "0")}:00`;
      const endTime = `${String(hour + 1).padStart(2, "0")}:00`;
      const startsAt = zonedDateTimeToUtc(date, startTime, timezone);
      const endsAt = zonedDateTimeToUtc(date, endTime, timezone);
      if (!startsAt || !endsAt || startsAt <= now) continue;
      operations.push({ updateOne: {
        filter: { date, startTime, endTime },
        update: { $setOnInsert: { date, startTime, endTime, startsAt, endsAt, timezone, source: "auto", notes: "Auto-generated daily discovery call slot.", isActive: true, isBooked: false, isAutoGenerated: true } },
        upsert: true,
      } });
    }
  }
  return operations;
};

const acquireLock = async () => {
  const now = new Date();
  try {
    return await MaintenanceLock.findOneAndUpdate(
      { name: LOCK_NAME, $or: [{ leaseExpiresAt: { $lte: now } }, { owner }] },
      { $set: { owner, leaseExpiresAt: new Date(now.getTime() + 5 * 60 * 1000) } },
      { new: true, upsert: true }
    );
  } catch (error) {
    if (error?.code === 11000) return null;
    throw error;
  }
};

const safeCleanup = async (now = new Date(), batchSize = 100, { includeLegacy = false } = {}) => {
  const query = {
    endsAt: { $lt: now }, isBooked: false, bookedBy: null,
    protectedFromCleanup: { $ne: true },
  };
  if (includeLegacy) {
    query.$or = [{ isAutoGenerated: true }, { source: "legacy" }, { source: { $exists: false } }];
  } else {
    query.isAutoGenerated = true;
  }
  const candidates = await CallSlot.find(query).sort({ endsAt: 1 }).limit(batchSize).select("_id").lean();
  if (!candidates.length) return 0;
  const ids = candidates.map((item) => item._id);
  const referenced = await Appointment.distinct("slot", { slot: { $in: ids } });
  const referencedSet = new Set(referenced.map(String));
  const safeIds = ids.filter((id) => !referencedSet.has(String(id)));
  if (!safeIds.length) return 0;
  const deleteQuery = {
    _id: { $in: safeIds }, isBooked: false, bookedBy: null,
    endsAt: { $lt: now }, protectedFromCleanup: { $ne: true },
  };
  if (includeLegacy) {
    deleteQuery.$or = [{ isAutoGenerated: true }, { source: "legacy" }, { source: { $exists: false } }];
  } else {
    deleteQuery.isAutoGenerated = true;
  }
  const result = await CallSlot.deleteMany(deleteQuery);
  return result.deletedCount;
};

const runSlotMaintenance = async ({ includeLegacyCleanup = false } = {}) => {
  if (running) return null;
  const lock = await acquireLock();
  if (!lock || lock.owner !== owner) return null;
  running = true;
  const startedAt = new Date();
  try {
    const operations = buildSlotOperations(startedAt);
    let ensured = 0;
    if (operations.length) {
      const result = await CallSlot.bulkWrite(operations, { ordered: false });
      ensured = result.upsertedCount || 0;
    }
    const cleaned = await safeCleanup(startedAt, 100, { includeLegacy: includeLegacyCleanup });
    const summary = { ensured, cleaned, completedAt: new Date() };
    await MaintenanceLock.updateOne({ name: LOCK_NAME, owner }, { $set: { lastSuccessAt: new Date(), lastResult: summary, leaseExpiresAt: new Date() } });
    return summary;
  } finally {
    running = false;
  }
};

const startSlotMaintenance = () => {
  if (timer || process.env.NODE_ENV === "test" || process.env.SLOT_MAINTENANCE_ENABLED === "false") return;
  const interval = Math.min(Math.max(Number(process.env.SLOT_MAINTENANCE_INTERVAL_MS) || 6 * 60 * 60 * 1000, 60000), 24 * 60 * 60 * 1000);
  timer = setInterval(() => void runSlotMaintenance().catch(() => {}), interval);
  timer.unref?.();
  void runSlotMaintenance().catch(() => {});
};
const stopSlotMaintenance = () => { if (timer) clearInterval(timer); timer = null; };
const getSlotMaintenanceStatus = async () => {
  const lock = await MaintenanceLock.findOne({ name: LOCK_NAME }).select("lastSuccessAt lastResult leaseExpiresAt").lean();
  return { initialized: Boolean(timer) || process.env.NODE_ENV === "test", running, ...lock };
};

module.exports = { buildSlotOperations, safeCleanup, runSlotMaintenance, startSlotMaintenance, stopSlotMaintenance, getSlotMaintenanceStatus };
