const crypto = require("crypto");
const CallSlot = require("../models/CallSlot");
const Appointment = require("../models/Appointment");
const MaintenanceLock = require("../models/MaintenanceLock");
const { log } = require("../utils/logger");
const {
  getBusinessTimezone,
  getBookingWindowDays,
  formatDateInZone,
  addCalendarDays,
  buildCanonicalSlotFields,
  bookingWindowEnd,
} = require("../utils/slotTime");

const LOCK_NAME = "slot-maintenance";
const CLEANUP_BATCH_LIMIT = 100;
const owner = `${process.pid}:${crypto.randomUUID()}`;
let timer = null;
let running = false;

const buildSlotOperations = (now = new Date()) => {
  const timezone = getBusinessTimezone();
  const today = formatDateInZone(now, timezone);
  const operations = [];
  for (let dayOffset = 0; dayOffset < getBookingWindowDays(); dayOffset += 1) {
    const date = addCalendarDays(today, dayOffset);
    for (let hour = 16; hour < 23; hour += 1) {
      const startTime = `${String(hour).padStart(2, "0")}:00`;
      const endTime = `${String(hour + 1).padStart(2, "0")}:00`;
      const fields = buildCanonicalSlotFields({ date, startTime, endTime, timezone });
      if (fields.startsAt <= now) continue;
      operations.push({ updateOne: {
        filter: { date, startTime, endTime },
        update: { $setOnInsert: { ...fields, source: "auto", notes: "Auto-generated daily discovery call slot.", isActive: true, isBooked: false, bookedBy: null, isAutoGenerated: true, protectedFromCleanup: false } },
        upsert: true,
      } });
    }
  }
  return operations;
};

const buildExpiredCleanupQuery = (now = new Date(), { includeLegacy = false } = {}) => {
  const query = {
    endsAt: { $type: "date", $lt: now },
    isBooked: false,
    bookedBy: null,
    protectedFromCleanup: { $ne: true },
  };
  if (includeLegacy) {
    query.$or = [{ isAutoGenerated: true }, { source: "legacy" }, { source: { $exists: false } }];
  } else {
    query.isAutoGenerated = true;
  }
  return query;
};

const buildOutsideHorizonCleanupQuery = (now = new Date()) => ({
  startsAt: { $type: "date", $gt: bookingWindowEnd(now) },
  endsAt: { $type: "date" },
  $expr: { $gt: ["$endsAt", "$startsAt"] },
  isAutoGenerated: true,
  source: { $ne: "manual" },
  isBooked: false,
  bookedBy: null,
  protectedFromCleanup: { $ne: true },
});

const findUnreferencedCleanupCandidates = async (query, { batchLimit = CLEANUP_BATCH_LIMIT, sort = { endsAt: 1, _id: 1 } } = {}) => {
  if (!Number.isInteger(batchLimit) || batchLimit < 1 || batchLimit > 1000) throw new Error("Cleanup batch limit must be between 1 and 1000");
  return CallSlot.aggregate([
    { $match: query },
    { $sort: sort },
    { $lookup: { from: Appointment.collection.name, localField: "_id", foreignField: "slot", as: "appointmentReferences" } },
    { $match: { "appointmentReferences.0": { $exists: false } } },
    { $limit: batchLimit },
    { $project: { _id: 1 } },
  ]);
};

const deleteCleanupCandidates = async (query, options) => {
  const candidates = await findUnreferencedCleanupCandidates(query, options);
  if (!candidates.length) return 0;
  const ids = candidates.map((item) => item._id);
  const referenced = await Appointment.distinct("slot", { slot: { $in: ids } });
  const referencedSet = new Set(referenced.map(String));
  const safeIds = ids.filter((id) => !referencedSet.has(String(id)));
  if (!safeIds.length) return 0;
  const result = await CallSlot.deleteMany({ ...query, _id: { $in: safeIds } });
  return result.deletedCount;
};

const safeCleanup = (now = new Date(), batchSize = CLEANUP_BATCH_LIMIT, { includeLegacy = false } = {}) =>
  deleteCleanupCandidates(buildExpiredCleanupQuery(now, { includeLegacy }), { batchLimit: batchSize, sort: { endsAt: 1, _id: 1 } });

const cleanOutsideHorizon = (now = new Date(), batchSize = CLEANUP_BATCH_LIMIT) =>
  deleteCleanupCandidates(buildOutsideHorizonCleanupQuery(now), { batchLimit: batchSize, sort: { startsAt: 1, _id: 1 } });

const countMissingSlotOperations = async (operations) => {
  if (!operations.length) return 0;
  const filters = operations.map((operation) => operation.updateOne.filter);
  const existing = await CallSlot.find({ $or: filters }).select("date startTime endTime").lean();
  const existingKeys = new Set(existing.map((slot) => `${slot.date}|${slot.startTime}|${slot.endTime}`));
  return filters.filter((filter) => !existingKeys.has(`${filter.date}|${filter.startTime}|${filter.endTime}`)).length;
};

const previewSlotMaintenance = async ({ now = new Date(), includeLegacyCleanup = false, batchLimit = CLEANUP_BATCH_LIMIT } = {}) => {
  const operations = buildSlotOperations(now);
  const [wouldEnsure, expiredCandidates, outsideHorizonCandidates] = await Promise.all([
    countMissingSlotOperations(operations),
    findUnreferencedCleanupCandidates(buildExpiredCleanupQuery(now, { includeLegacy: includeLegacyCleanup }), { batchLimit, sort: { endsAt: 1, _id: 1 } }),
    findUnreferencedCleanupCandidates(buildOutsideHorizonCleanupQuery(now), { batchLimit, sort: { startsAt: 1, _id: 1 } }),
  ]);
  const wouldCleanExpired = expiredCandidates.length;
  const wouldCleanOutsideHorizon = outsideHorizonCandidates.length;
  return {
    wouldEnsure,
    wouldCleanExpired,
    wouldCleanOutsideHorizon,
    totalWouldClean: wouldCleanExpired + wouldCleanOutsideHorizon,
    batchLimit,
  };
};

const acquireLock = async () => {
  const now = new Date();
  try {
    return await MaintenanceLock.findOneAndUpdate(
      { name: LOCK_NAME, $or: [{ leaseExpiresAt: { $lte: now } }, { owner }] },
      { $set: { owner, leaseExpiresAt: new Date(now.getTime() + 5 * 60 * 1000) } },
      { new: true, upsert: true }
    );
  } catch (error) {
    if (error?.code === 11000) return null;
    throw error;
  }
};

const runSlotMaintenance = async ({ includeLegacyCleanup = false, batchLimit = CLEANUP_BATCH_LIMIT, trigger = "direct" } = {}) => {
  if (running) return null;
  const lock = await acquireLock();
  if (!lock || lock.owner !== owner) return null;
  running = true;
  const startedAt = new Date();
  try {
    const operations = buildSlotOperations(startedAt);
    let slotsEnsured = 0;
    if (operations.length) {
      const result = await CallSlot.bulkWrite(operations, { ordered: false });
      slotsEnsured = result.upsertedCount || 0;
    }
    const [expiredSlotsCleaned, outsideHorizonSlotsCleaned] = await Promise.all([
      safeCleanup(startedAt, batchLimit, { includeLegacy: includeLegacyCleanup }),
      cleanOutsideHorizon(startedAt, batchLimit),
    ]);
    const summary = {
      slotsEnsured,
      expiredSlotsCleaned,
      outsideHorizonSlotsCleaned,
      totalSlotsCleaned: expiredSlotsCleaned + outsideHorizonSlotsCleaned,
      batchLimit,
      trigger,
      completedAt: new Date(),
    };
    await MaintenanceLock.updateOne({ name: LOCK_NAME, owner }, { $set: { lastSuccessAt: new Date(), lastResult: summary, leaseExpiresAt: new Date() } });
    return summary;
  } finally {
    running = false;
  }
};

const isAutomaticSlotMaintenanceEnabled = () => String(process.env.SLOT_MAINTENANCE_ENABLED || "").toLowerCase() === "true";

const startSlotMaintenance = ({ runMaintenance = runSlotMaintenance, setIntervalFn = setInterval, logFn = log } = {}) => {
  if (timer) return false;
  if (!isAutomaticSlotMaintenanceEnabled()) {
    logFn("info", "slot_maintenance_disabled", { reason: "SLOT_MAINTENANCE_ENABLED is not true" });
    return false;
  }
  const interval = Math.min(Math.max(Number(process.env.SLOT_MAINTENANCE_INTERVAL_MS) || 6 * 60 * 60 * 1000, 60000), 24 * 60 * 60 * 1000);
  const execute = async () => {
    try {
      const result = await runMaintenance({ trigger: "automatic" });
      if (result) {
        logFn("info", "slot_maintenance_completed", {
          trigger: "automatic",
          slotsEnsured: result.slotsEnsured,
          expiredSlotsCleaned: result.expiredSlotsCleaned,
          outsideHorizonSlotsCleaned: result.outsideHorizonSlotsCleaned,
        });
      }
    } catch (error) {
      logFn("error", "slot_maintenance_failed", { trigger: "automatic", code: error.code || error.name });
    }
  };
  timer = setIntervalFn(() => void execute(), interval);
  timer.unref?.();
  logFn("info", "slot_maintenance_started", { intervalMs: interval });
  void execute();
  return true;
};
const stopSlotMaintenance = () => { if (timer) clearInterval(timer); timer = null; };
const getSlotMaintenanceStatus = async () => {
  const lock = await MaintenanceLock.findOne({ name: LOCK_NAME }).select("lastSuccessAt lastResult leaseExpiresAt").lean();
  const enabled = isAutomaticSlotMaintenanceEnabled();
  return { enabled, initialized: !enabled || Boolean(timer), running, ...lock };
};

module.exports = {
  CLEANUP_BATCH_LIMIT,
  buildSlotOperations,
  buildExpiredCleanupQuery,
  buildOutsideHorizonCleanupQuery,
  findUnreferencedCleanupCandidates,
  safeCleanup,
  cleanOutsideHorizon,
  previewSlotMaintenance,
  runSlotMaintenance,
  isAutomaticSlotMaintenanceEnabled,
  startSlotMaintenance,
  stopSlotMaintenance,
  getSlotMaintenanceStatus,
};
