const CallSlot = require("../models/CallSlot");
const { buildCanonicalSlotFields } = require("../utils/slotTime");

const legacySlotQuery = {
  $or: [
    { startsAt: null },
    { endsAt: null },
    { startsAt: { $exists: false } },
    { endsAt: { $exists: false } },
  ],
};

const runSlotBackfill = async ({ apply = false, batchSize = 200 } = {}) => {
  if (!Number.isInteger(batchSize) || batchSize < 1 || batchSize > 1000) {
    throw new Error("Slot backfill batch size must be between 1 and 1000");
  }

  const beforeCandidates = await CallSlot.countDocuments(legacySlotQuery);
  let lastId = null;
  let scanned = 0;
  let convertible = 0;
  let modified = 0;
  const malformedIds = [];

  while (true) {
    const pageQuery = lastId ? { $and: [legacySlotQuery, { _id: { $gt: lastId } }] } : legacySlotQuery;
    const slots = await CallSlot.find(pageQuery)
      .sort({ _id: 1 })
      .limit(batchSize)
      .select("date startTime endTime timezone source isAutoGenerated")
      .lean();
    if (!slots.length) break;

    const operations = [];
    for (const slot of slots) {
      scanned += 1;
      try {
        const fields = buildCanonicalSlotFields({
          date: slot.date,
          startTime: slot.startTime,
          endTime: slot.endTime,
          timezone: slot.timezone || "Africa/Cairo",
        });
        const { startsAt, endsAt, timezone } = fields;
        const inferredSource = slot.source || (slot.isAutoGenerated ? "auto" : "legacy");
        convertible += 1;
        operations.push({
          updateOne: {
            filter: { _id: slot._id, ...legacySlotQuery },
            update: { $set: { startsAt, endsAt, timezone, source: inferredSource } },
          },
        });
      } catch {
        malformedIds.push(String(slot._id));
      }
    }

    if (apply && operations.length) {
      const result = await CallSlot.bulkWrite(operations, { ordered: false });
      modified += result.modifiedCount;
    }
    lastId = slots.at(-1)._id;
  }

  const afterCandidates = apply ? await CallSlot.countDocuments(legacySlotQuery) : beforeCandidates;
  return {
    beforeCandidates,
    scanned,
    convertible,
    modified,
    afterCandidates,
    malformedCount: malformedIds.length,
    malformedSampleIds: malformedIds.slice(0, 20),
  };
};

module.exports = { legacySlotQuery, runSlotBackfill };
