const path = require("path");
require("dotenv").config({ path: path.resolve(__dirname, "../../.env"), override: false, quiet: true });

const test = require("node:test");
const assert = require("node:assert/strict");
const mongoose = require("mongoose");
const { assertTestDatabaseSafety } = require("../../utils/testDatabaseSafety");

const databaseSafety = assertTestDatabaseSafety({
  productionUri: process.env.MONGO_URI,
  testUri: process.env.MONGO_TEST_URI,
});

process.env.NODE_ENV = "test";
process.env.EMAIL_OUTBOX_ENABLED = "false";
process.env.SLOT_MAINTENANCE_ENABLED = "false";
process.env.JWT_SECRET = "integration-jwt-secret-which-is-independent";
process.env.REFRESH_TOKEN_SECRET = "integration-refresh-secret-which-is-independent";
process.env.OUTBOX_ENCRYPTION_KEY = "a".repeat(64);
process.env.CLIENT_URL = "http://localhost:5173";
process.env.ALLOWED_ORIGINS = "http://localhost:5173";
process.env.BUSINESS_TIMEZONE = "Africa/Cairo";
process.env.BOOKING_WINDOW_DAYS = "7";

const Appointment = require("../../models/Appointment");
const CallSlot = require("../../models/CallSlot");
const Contract = require("../../models/Contract");
const EmailOutbox = require("../../models/EmailOutbox");
const IdempotencyRecord = require("../../models/IdempotencyRecord");
const MaintenanceLock = require("../../models/MaintenanceLock");
const RateLimitRecord = require("../../models/RateLimitRecord");
const RefreshSession = require("../../models/RefreshSession");
const User = require("../../models/User");
const WebsiteRequest = require("../../models/WebsiteRequest");
const { runSlotBackfill } = require("../../services/slotBackfillService");
const { reconcileSlots } = require("../../services/slotReconciliationService");
const { previewSlotMaintenance, runSlotMaintenance, safeCleanup } = require("../../services/slotMaintenanceService");
const { enqueueEmail } = require("../../services/outboxService");
const { claimNext, processOne } = require("../../services/outboxWorker");
const { createRefreshSession, rotateRefreshSession } = require("../../services/refreshSessionService");
const { runIdempotentTransaction } = require("../../services/idempotencyService");
const { withMongoTransaction } = require("../../services/transactionService");
const { linkVerifiedGuestRecords } = require("../../utils/linkGuestRecords");
const { addCalendarDays, bookingWindowEnd, formatDateInZone, zonedDateTimeToUtc } = require("../../utils/slotTime");

const collections = [
  Appointment, CallSlot, Contract, EmailOutbox, IdempotencyRecord,
  MaintenanceLock, RateLimitRecord, RefreshSession, User, WebsiteRequest,
];
let connected = false;

const cleanTestData = async () => {
  for (const model of collections) await model.deleteMany({});
};

const insertRawCallSlots = async (documents) => {
  const timestamp = new Date();
  const records = documents.map((document) => ({
    _id: new mongoose.Types.ObjectId(),
    isBooked: false,
    bookedBy: null,
    isActive: true,
    notes: "",
    isAutoGenerated: false,
    protectedFromCleanup: false,
    createdAt: timestamp,
    updatedAt: timestamp,
    ...document,
  }));
  await CallSlot.collection.insertMany(records);
  return Promise.all(records.map((record) => CallSlot.findById(record._id)));
};

test.before(async () => {
  await mongoose.connect(process.env.MONGO_TEST_URI, { serverSelectionTimeoutMS: 10000 });
  connected = true;
  assert.equal(mongoose.connection.name, databaseSafety.testDatabaseName);
  await Promise.all(collections.map((model) => model.createIndexes()));
});

test.beforeEach(cleanTestData);

test.after(async () => {
  if (!connected) return;
  await cleanTestData();
  await mongoose.disconnect();
});

test("transactions roll back business records and atomic outbox events together", async () => {
  await assert.rejects(withMongoTransaction(async (session) => {
    const [contract] = await Contract.create([{
      title: "Rollback fixture",
      clientName: "Test Client",
      clientEmail: "rollback@integration.test",
      websiteType: "Business",
      scopeSummary: "Transaction rollback fixture",
    }], { session });
    await enqueueEmail({
      eventType: "contract.created",
      idempotencyKey: `contract:${contract._id}:created`,
      relatedEntityType: "Contract",
      relatedEntityId: contract._id,
      recipientType: "client",
      recipient: "rollback@integration.test",
      template: "contract.client",
      templatePayload: { title: "Contract created", rows: [] },
    }, { session });
    throw new Error("intentional rollback");
  }), /intentional rollback/);
  assert.equal(await Contract.countDocuments({}), 0);
  assert.equal(await EmailOutbox.countDocuments({}), 0);
});

test("twelve concurrent bookings produce exactly one consistent appointment", async () => {
  const slot = await CallSlot.create({
    date: "2030-01-01", startTime: "16:00", endTime: "16:30",
    startsAt: new Date("2030-01-01T14:00:00Z"), endsAt: new Date("2030-01-01T14:30:00Z"),
  });
  const attempts = await Promise.allSettled(Array.from({ length: 12 }, (_, index) => withMongoTransaction(async (session) => {
    const appointmentId = new mongoose.Types.ObjectId();
    const claimed = await CallSlot.findOneAndUpdate(
      { _id: slot._id, isBooked: false, bookedBy: null },
      { $set: { isBooked: true, bookedBy: appointmentId } },
      { new: true, session }
    );
    if (!claimed) throw new Error("slot unavailable");
    const [appointment] = await Appointment.create([{
      _id: appointmentId,
      slot: slot._id,
      name: `Booking ${index}`,
      phone: "+201000000000",
      email: `booking-${index}@integration.test`,
      topic: "Concurrency fixture",
    }], { session });
    return appointment._id;
  })));
  assert.equal(attempts.filter((result) => result.status === "fulfilled").length, 1);
  const appointments = await Appointment.find({ slot: slot._id }).lean();
  const booked = await CallSlot.findById(slot._id).lean();
  assert.equal(appointments.length, 1);
  assert.equal(booked.isBooked, true);
  assert.equal(String(booked.bookedBy), String(appointments[0]._id));
});

test("outbox deduplicates, claims atomically, recovers stale leases, and uses fake delivery", async () => {
  const makeEvent = (suffix) => ({
    eventType: "account.verification",
    idempotencyKey: `integration:outbox:${suffix}`,
    relatedEntityType: "User",
    recipientType: "client",
    recipient: "outbox@integration.test",
    template: "account.verification",
    templatePayload: { name: "Integration Client" },
    sensitivePayload: { token: "fixture-token" },
  });
  await Promise.all(Array.from({ length: 12 }, () => enqueueEmail(makeEvent("dedupe"))));
  assert.equal(await EmailOutbox.countDocuments({ idempotencyKey: "integration:outbox:dedupe" }), 1);

  await Promise.all([enqueueEmail(makeEvent("claim-a")), enqueueEmail(makeEvent("claim-b"))]);
  const claims = (await Promise.all(Array.from({ length: 6 }, () => claimNext()))).filter(Boolean);
  assert.equal(claims.length, 3);
  assert.equal(new Set(claims.map((event) => String(event._id))).size, 3);

  await EmailOutbox.updateMany({}, { $set: { status: "delivered", deliveredAt: new Date() } });
  await enqueueEmail(makeEvent("stale"));
  await EmailOutbox.updateOne(
    { idempotencyKey: "integration:outbox:stale" },
    { $set: { status: "processing", leaseExpiresAt: new Date(Date.now() - 1000), lockedAt: new Date(Date.now() - 2000) } }
  );
  const recovered = await claimNext();
  assert.equal(recovered.idempotencyKey, "integration:outbox:stale");
  assert.equal(recovered.attempts, 1);

  await EmailOutbox.updateOne({ _id: recovered._id }, { $set: { status: "pending", nextAttemptAt: new Date(), leaseExpiresAt: null } });
  let sends = 0;
  assert.equal(await processOne({ send: async () => { sends += 1; return { messageId: "fake-message" }; } }), true);
  assert.equal(sends, 1);
  assert.equal((await EmailOutbox.findById(recovered._id).lean()).status, "delivered");
});

test("refresh rotation detects reuse and revokes the entire session family", async () => {
  const user = await User.create({
    name: "Integration Client", email: "auth@integration.test", phone: "+201000000000",
    password: "correct horse battery staple", role: "client", emailVerifiedAt: new Date(),
  });
  const req = { get: () => "node-test" };
  const created = await createRefreshSession(user, req);
  const results = await Promise.all([
    rotateRefreshSession(created.token, req),
    rotateRefreshSession(created.token, req),
  ]);
  assert.equal(results.filter((item) => item.token).length, 1);
  assert.equal(results.filter((item) => item.error === "reuse").length, 1);
  assert.equal(await RefreshSession.countDocuments({ sessionFamily: created.refreshSession.sessionFamily, revokedAt: null }), 0);
});

test("guest records are claimed only by a verified matching client inside a transaction", async () => {
  const verifiedUser = await User.create({
    name: "Verified Client", email: "claim@integration.test", phone: "+201000000010",
    password: "correct horse battery staple", role: "client", emailVerifiedAt: new Date(),
  });
  const unverifiedUser = {
    _id: new mongoose.Types.ObjectId(),
    email: "claim@integration.test",
    role: "client",
    emailVerifiedAt: null,
  };
  const matchingRequest = await WebsiteRequest.create({
    name: "Matching Guest", phone: "+201000000012", email: "claim@integration.test",
    websiteType: "Business Website", projectDetails: "Verified guest claim fixture",
  });
  const otherRequest = await WebsiteRequest.create({
    name: "Other Guest", phone: "+201000000013", email: "other@integration.test",
    websiteType: "Business Website", projectDetails: "Must remain unclaimed",
  });
  const archivedRequest = await WebsiteRequest.create({
    name: "Archived Guest", phone: "+201000000014", email: "claim@integration.test",
    websiteType: "Business Website", projectDetails: "Archived records stay unclaimed",
    archivedAt: new Date(),
  });
  const slot = await CallSlot.create({
    date: "2030-01-02", startTime: "16:00", endTime: "16:30",
    startsAt: new Date("2030-01-02T14:00:00Z"), endsAt: new Date("2030-01-02T14:30:00Z"),
  });
  const matchingAppointment = await Appointment.create({
    slot: slot._id, name: "Matching Guest", phone: "+201000000015",
    email: "claim@integration.test", topic: "Verified guest claim fixture",
  });
  const matchingContract = await Contract.create({
    request: matchingRequest._id,
    title: "Guest claim contract", clientName: "Matching Guest",
    clientEmail: "claim@integration.test", websiteType: "Business Website",
    scopeSummary: "Contract follows its verified matching request",
  });

  assert.deepEqual(await linkVerifiedGuestRecords(unverifiedUser), {
    linkedRequests: 0,
    linkedAppointments: 0,
    linkedContracts: 0,
  });
  await assert.rejects(
    linkVerifiedGuestRecords(verifiedUser),
    /require a MongoDB transaction/,
  );

  const claimed = await withMongoTransaction((session) =>
    linkVerifiedGuestRecords(verifiedUser, { session, auditKey: "integration:verified-claim" })
  );
  assert.deepEqual(claimed, {
    linkedRequests: 1,
    linkedAppointments: 1,
    linkedContracts: 1,
  });
  assert.equal(String((await WebsiteRequest.findById(matchingRequest._id).lean()).client), String(verifiedUser._id));
  assert.equal(String((await Appointment.findById(matchingAppointment._id).lean()).client), String(verifiedUser._id));
  assert.equal(String((await Contract.findById(matchingContract._id).lean()).client), String(verifiedUser._id));
  assert.equal((await WebsiteRequest.findById(otherRequest._id).lean()).client, null);
  assert.equal((await WebsiteRequest.findById(archivedRequest._id).lean()).client, null);

  const repeated = await withMongoTransaction((session) =>
    linkVerifiedGuestRecords(verifiedUser, { session, auditKey: "integration:verified-claim-repeat" })
  );
  assert.deepEqual(repeated, {
    linkedRequests: 0,
    linkedAppointments: 0,
    linkedContracts: 0,
  });
});

test("contract creation is idempotent", async () => {
  const req = { ip: "127.0.0.1", get: (name) => name === "Idempotency-Key" ? "integration-contract-key-0001" : "" };
  const payload = { title: "Idempotent fixture", clientEmail: "contract@integration.test" };
  const work = (session) => Contract.create([{
    title: payload.title,
    clientName: "Integration Client",
    clientEmail: payload.clientEmail,
    websiteType: "Business",
    scopeSummary: "Idempotency fixture",
  }], { session }).then(([contract]) => ({ contractId: String(contract._id), notificationStatus: "queued" }));
  const first = await runIdempotentTransaction({ req, scope: "contract.create", actor: "admin", payload, work });
  const second = await runIdempotentTransaction({ req, scope: "contract.create", actor: "admin", payload, work });
  assert.equal(first.contractId, second.contractId);
  assert.equal(second.replayed, true);
  assert.equal(await Contract.countDocuments({}), 1);
});

test("legacy slot backfill is bounded, timezone-correct, idempotent, and cleanup-safe", async () => {
  const now = new Date();
  const today = formatDateInZone(now, "Africa/Cairo");
  const yesterday = addCalendarDays(today, -1);
  const tomorrow = addCalendarDays(today, 1);
  const outside = addCalendarDays(today, 7);

  const [expiredUnbooked, expiredBooked, futureInWindow, futureOutsideWindow] = await insertRawCallSlots([
    { date: yesterday, startTime: "09:00", endTime: "09:30", source: "legacy" },
    { date: yesterday, startTime: "10:00", endTime: "10:30", source: "legacy" },
    { date: tomorrow, startTime: "11:00", endTime: "11:30", source: "legacy" },
    { date: outside, startTime: "12:00", endTime: "12:30", source: "legacy" },
  ]);
  const appointment = await Appointment.create({
    slot: expiredBooked._id, name: "Historical booking", phone: "+201000000000",
    email: "historical@integration.test", topic: "Referenced slot fixture",
  });
  await CallSlot.updateOne({ _id: expiredBooked._id }, { $set: { isBooked: true, bookedBy: appointment._id } });

  assert.equal((await reconcileSlots()).counts.malformedSlots, 4);
  const result = await runSlotBackfill({ apply: true, batchSize: 2 });
  assert.deepEqual({ before: result.beforeCandidates, scanned: result.scanned, convertible: result.convertible, modified: result.modified, after: result.afterCandidates, malformed: result.malformedCount }, {
    before: 4, scanned: 4, convertible: 4, modified: 4, after: 0, malformed: 0,
  });
  const converted = await CallSlot.findById(futureInWindow._id).lean();
  assert.equal(converted.startsAt.toISOString(), zonedDateTimeToUtc(tomorrow, "11:00", "Africa/Cairo").toISOString());
  assert.equal(converted.endsAt.toISOString(), zonedDateTimeToUtc(tomorrow, "11:30", "Africa/Cairo").toISOString());
  assert.equal(converted.date, tomorrow);
  assert.equal(converted.startTime, "11:00");
  assert.equal(converted.endTime, "11:30");
  assert.equal((await reconcileSlots()).counts.malformedSlots, 0);
  assert.equal((await reconcileSlots()).counts.expiredUnbookedCandidates, 1);
  const rerun = await runSlotBackfill({ apply: true, batchSize: 2 });
  assert.equal(rerun.modified, 0);
  assert.equal(rerun.beforeCandidates, 0);

  const visibleFutureIds = await CallSlot.find({ startsAt: { $gt: now, $lte: bookingWindowEnd(now) } }).distinct("_id");
  assert.equal(visibleFutureIds.map(String).includes(String(futureInWindow._id)), true);
  assert.equal(visibleFutureIds.map(String).includes(String(futureOutsideWindow._id)), false);

  assert.equal(await safeCleanup(now, 100, { includeLegacy: true }), 1);
  assert.equal(await CallSlot.exists({ _id: expiredUnbooked._id }), null);
  assert.ok(await CallSlot.exists({ _id: expiredBooked._id }));
  assert.ok(await Appointment.exists({ _id: appointment._id }));
});

test("seven legacy auto slots are previewed as convertible and reconcile cleanly after fixture backfill", async () => {
  const today = formatDateInZone(new Date(), "Africa/Cairo");
  const date = addCalendarDays(today, 1);
  await insertRawCallSlots(Array.from({ length: 7 }, (_, index) => ({
    date,
    startTime: `${String(16 + index).padStart(2, "0")}:00`,
    endTime: `${String(17 + index).padStart(2, "0")}:00`,
    timezone: "Africa/Cairo",
    isAutoGenerated: true,
  })));

  const before = await reconcileSlots();
  assert.equal(before.counts.malformedSlots, 7);
  const preview = await runSlotBackfill({ apply: false, batchSize: 3 });
  assert.deepEqual(
    { before: preview.beforeCandidates, scanned: preview.scanned, convertible: preview.convertible, modified: preview.modified, malformed: preview.malformedCount },
    { before: 7, scanned: 7, convertible: 7, modified: 0, malformed: 0 }
  );
  const applied = await runSlotBackfill({ apply: true, batchSize: 3 });
  assert.equal(applied.modified, 7);
  assert.equal(applied.afterCandidates, 0);
  assert.equal(await CallSlot.countDocuments({ source: "auto", isAutoGenerated: true }), 7);
  assert.equal((await reconcileSlots()).counts.malformedSlots, 0);
});

test("horizon maintenance persists only canonical auto slots and is idempotent", async () => {
  const first = await runSlotMaintenance({ trigger: "automatic" });
  assert.ok(first.slotsEnsured > 0 && first.slotsEnsured <= 49);
  const slots = await CallSlot.find({ source: "auto", isAutoGenerated: true }).lean();
  assert.equal(slots.length, first.slotsEnsured);
  for (const slot of slots) {
    assert.ok(slot.startsAt instanceof Date);
    assert.ok(slot.endsAt instanceof Date);
    assert.ok(slot.endsAt > slot.startsAt);
    assert.equal(slot.timezone, "Africa/Cairo");
    assert.equal(slot.isBooked, false);
    assert.equal(slot.bookedBy, null);
    assert.equal(slot.isActive, true);
  }
  const second = await runSlotMaintenance({ trigger: "automatic" });
  assert.equal(second.slotsEnsured, 0);
  assert.equal(second.totalSlotsCleaned, 0);
  assert.equal(await CallSlot.countDocuments({ source: "auto", isAutoGenerated: true }), slots.length);
});

test("maintenance safely prunes outside-horizon auto slots in bounded, idempotent batches", async () => {
  const now = new Date();
  const today = formatDateInZone(now, "Africa/Cairo");
  const slotFixture = (dayOffset, startTime, endTime, overrides = {}) => {
    const date = addCalendarDays(today, dayOffset);
    return {
      date,
      startTime,
      endTime,
      startsAt: zonedDateTimeToUtc(date, startTime, "Africa/Cairo"),
      endsAt: zonedDateTimeToUtc(date, endTime, "Africa/Cairo"),
      timezone: "Africa/Cairo",
      source: "auto",
      isAutoGenerated: true,
      ...overrides,
    };
  };

  const removable = await CallSlot.insertMany(Array.from({ length: 105 }, (_, index) =>
    slotFixture(7 + index, "09:00", "09:30")
  ));
  const expired = await CallSlot.create(slotFixture(-1, "08:00", "08:30"));
  const insideWindow = await CallSlot.create(slotFixture(1, "13:00", "13:30"));
  const manualOutside = await CallSlot.create(slotFixture(150, "10:00", "10:30", { source: "manual", isAutoGenerated: false }));
  const [explicitlyManualOutside] = await insertRawCallSlots([slotFixture(151, "10:00", "10:30", { source: "manual", isAutoGenerated: true })]);
  const protectedOutside = await CallSlot.create(slotFixture(152, "10:00", "10:30", { protectedFromCleanup: true }));
  const [invalidOutside] = await insertRawCallSlots([slotFixture(155, "10:00", "10:30", { endsAt: null })]);
  const referencedOutside = await CallSlot.create(slotFixture(153, "10:00", "10:30"));
  const referencedAppointment = await Appointment.create({
    slot: referencedOutside._id,
    name: "Referenced fixture",
    phone: "+201000000001",
    email: "referenced-slot@integration.test",
    topic: "Outside-horizon safety",
    status: "Cancelled",
    holdsSlot: false,
  });
  const bookedOutside = await CallSlot.create(slotFixture(154, "10:00", "10:30"));
  const bookedAppointment = await Appointment.create({
    slot: bookedOutside._id,
    name: "Booked fixture",
    phone: "+201000000002",
    email: "booked-slot@integration.test",
    topic: "Outside-horizon safety",
  });
  await CallSlot.updateOne({ _id: bookedOutside._id }, { $set: { isBooked: true, bookedBy: bookedAppointment._id } });
  const contract = await Contract.create({
    appointment: referencedAppointment._id,
    title: "Preserved contract fixture",
    clientName: "Integration Client",
    clientEmail: "contract-slot@integration.test",
    websiteType: "Business",
    scopeSummary: "Contract must survive slot maintenance",
  });

  const preview = await previewSlotMaintenance({ now, includeLegacyCleanup: true, batchLimit: 100 });
  assert.equal(preview.wouldCleanExpired, 1);
  assert.equal(preview.wouldCleanOutsideHorizon, 100);
  assert.equal(preview.totalWouldClean, 101);
  assert.equal(preview.batchLimit, 100);
  assert.equal(await MaintenanceLock.countDocuments({}), 0);
  assert.equal(await CallSlot.countDocuments({ _id: { $in: removable.map((slot) => slot._id) } }), 105);
  assert.ok(await CallSlot.exists({ _id: expired._id }));

  const before = await reconcileSlots();
  assert.equal(before.counts.expiredUnbookedCandidates, 1);
  assert.equal(before.counts.generatedSlotsOutsideHorizon, 105);

  const first = await runSlotMaintenance({ includeLegacyCleanup: true, batchLimit: 100 });
  assert.equal(first.expiredSlotsCleaned, 1);
  assert.equal(first.outsideHorizonSlotsCleaned, 100);
  assert.equal(first.totalSlotsCleaned, 101);
  assert.equal(await CallSlot.exists({ _id: expired._id }), null);
  assert.equal((await reconcileSlots()).counts.generatedSlotsOutsideHorizon, 5);

  const second = await runSlotMaintenance({ includeLegacyCleanup: true, batchLimit: 100 });
  assert.equal(second.expiredSlotsCleaned, 0);
  assert.equal(second.outsideHorizonSlotsCleaned, 5);
  assert.equal(second.totalSlotsCleaned, 5);
  const after = await reconcileSlots();
  assert.equal(after.counts.expiredUnbookedCandidates, 0);
  assert.equal(after.counts.generatedSlotsOutsideHorizon, 0);

  const third = await runSlotMaintenance({ includeLegacyCleanup: true, batchLimit: 100 });
  assert.equal(third.expiredSlotsCleaned, 0);
  assert.equal(third.outsideHorizonSlotsCleaned, 0);
  assert.equal(third.totalSlotsCleaned, 0);

  assert.ok(await CallSlot.exists({ _id: insideWindow._id }));
  assert.ok(await CallSlot.exists({ _id: manualOutside._id }));
  assert.ok(await CallSlot.exists({ _id: explicitlyManualOutside._id }));
  assert.ok(await CallSlot.exists({ _id: protectedOutside._id }));
  assert.ok(await CallSlot.exists({ _id: invalidOutside._id }));
  assert.ok(await CallSlot.exists({ _id: referencedOutside._id }));
  assert.ok(await CallSlot.exists({ _id: bookedOutside._id }));
  assert.equal(await Appointment.countDocuments({ _id: { $in: [referencedAppointment._id, bookedAppointment._id] } }), 2);
  assert.ok(await Contract.exists({ _id: contract._id }));
  assert.equal(await CallSlot.countDocuments({ _id: { $in: removable.map((slot) => slot._id) } }), 0);
});
