const CallSlot = require("../models/CallSlot");
const Appointment = require("../models/Appointment");
const asyncHandler = require("../middleware/asyncHandler");
const { cleanText, cleanBoolean } = require("../utils/validation");
const { parsePagination, paginationMeta } = require("../utils/pagination");
const {
  datePattern, timePattern, getBusinessTimezone, getBookingWindowDays,
  formatDateInZone, addCalendarDays, zonedDateTimeToUtc, bookingWindowEnd,
} = require("../utils/slotTime");
const { runSlotMaintenance } = require("../services/slotMaintenanceService");

const validDate = (value) => datePattern.test(String(value)) && new Date(`${value}T00:00:00Z`).toISOString().slice(0, 10) === value;
const parseSlotTimes = ({ date, startTime, endTime, timezone = getBusinessTimezone() }) => {
  if (!validDate(date)) throw Object.assign(new Error("Date must be a valid YYYY-MM-DD date"), { statusCode: 400 });
  if (!timePattern.test(String(startTime)) || !timePattern.test(String(endTime))) throw Object.assign(new Error("Start and end time must use HH:mm format"), { statusCode: 400 });
  const startsAt = zonedDateTimeToUtc(date, startTime, timezone);
  const endsAt = zonedDateTimeToUtc(date, endTime, timezone);
  if (!startsAt || !endsAt || endsAt <= startsAt) throw Object.assign(new Error("End time must be after start time"), { statusCode: 400 });
  return { startsAt, endsAt, timezone };
};

const findOverlap = ({ startsAt, endsAt, excludeId }) => CallSlot.findOne({
  _id: excludeId ? { $ne: excludeId } : { $exists: true },
  isActive: true,
  startsAt: { $lt: endsAt },
  endsAt: { $gt: startsAt },
});

const createCallSlot = asyncHandler(async (req, res) => {
  const date = cleanText(req.body?.date, "Date", { required: true, max: 10 });
  const startTime = cleanText(req.body?.startTime, "Start time", { required: true, max: 5 });
  const endTime = cleanText(req.body?.endTime, "End time", { required: true, max: 5 });
  const times = parseSlotTimes({ date, startTime, endTime });
  if (await findOverlap(times)) { res.status(409); throw new Error("This slot overlaps an existing active slot"); }
  const slot = await CallSlot.create({ date, startTime, endTime, ...times, notes: cleanText(req.body?.notes, "Notes", { max: 500 }), source: "manual", isAutoGenerated: false });
  res.status(201).json({ success: true, message: "Call slot created successfully", slot });
});

const getAvailableSlots = asyncHandler(async (req, res) => {
  const now = new Date();
  const slots = await CallSlot.find({
    startsAt: { $gt: now, $lte: bookingWindowEnd(now) },
    isActive: true, isBooked: false, bookedBy: null,
  }).sort({ startsAt: 1 }).limit(getBookingWindowDays() * 24).lean();
  res.set("Cache-Control", "public, max-age=30, stale-while-revalidate=60");
  res.json({ success: true, count: slots.length, slots });
});

const getAllSlots = asyncHandler(async (req, res) => {
  const { page, limit, skip, sort } = parsePagination(req.query, { defaultLimit: 50, sortFields: ["startsAt", "createdAt", "updatedAt"], defaultSort: "startsAt", defaultDirection: "asc" });
  const query = {};
  if (req.query.state === "upcoming") query.startsAt = { $gt: new Date() };
  if (req.query.state === "expired") query.endsAt = { $lt: new Date() };
  if (req.query.isActive !== undefined) query.isActive = req.query.isActive === "true";
  if (req.query.isBooked !== undefined) query.isBooked = req.query.isBooked === "true";
  const [slots, total] = await Promise.all([CallSlot.find(query).sort(sort).skip(skip).limit(limit).lean(), CallSlot.countDocuments(query)]);
  res.json({ success: true, data: slots, slots, count: slots.length, pagination: paginationMeta({ page, limit, total }) });
});

const updateCallSlot = asyncHandler(async (req, res) => {
  const slot = await CallSlot.findById(req.params.id);
  if (!slot) { res.status(404); throw new Error("Call slot not found"); }
  const date = req.body.date === undefined ? slot.date : cleanText(req.body.date, "Date", { required: true, max: 10 });
  const startTime = req.body.startTime === undefined ? slot.startTime : cleanText(req.body.startTime, "Start time", { required: true, max: 5 });
  const endTime = req.body.endTime === undefined ? slot.endTime : cleanText(req.body.endTime, "End time", { required: true, max: 5 });
  const times = parseSlotTimes({ date, startTime, endTime, timezone: slot.timezone || getBusinessTimezone() });
  if (slot.isBooked && (date !== slot.date || startTime !== slot.startTime || endTime !== slot.endTime)) { res.status(409); throw new Error("A booked slot cannot be rescheduled directly"); }
  if (await findOverlap({ ...times, excludeId: slot._id })) { res.status(409); throw new Error("This slot overlaps an existing active slot"); }
  if (req.body.isBooked !== undefined && req.body.isBooked !== slot.isBooked) { res.status(400); throw new Error("Slot booking status is managed by appointments"); }
  const nextActive = req.body.isActive === undefined ? slot.isActive : cleanBoolean(req.body.isActive, "isActive");
  if (slot.isBooked && !nextActive) { res.status(409); throw new Error("Cannot disable a booked slot"); }
  Object.assign(slot, { date, startTime, endTime, ...times, isActive: nextActive });
  if (req.body.notes !== undefined) slot.notes = cleanText(req.body.notes, "Notes", { max: 500 });
  await slot.save();
  res.json({ success: true, message: "Call slot updated successfully", slot });
});

const deleteCallSlot = asyncHandler(async (req, res) => {
  const slot = await CallSlot.findById(req.params.id);
  if (!slot) { res.status(404); throw new Error("Call slot not found"); }
  if (slot.isBooked || (await Appointment.exists({ slot: slot._id }))) { res.status(409); throw new Error("Referenced slots cannot be deleted"); }
  slot.isActive = false;
  slot.protectedFromCleanup = !slot.isAutoGenerated;
  slot.notes = `${slot.notes ? `${slot.notes}\n` : ""}Hidden by admin.`;
  await slot.save();
  res.json({ success: true, message: "Call slot hidden successfully", slot });
});

const maintainSlots = asyncHandler(async (req, res) => {
  const result = await runSlotMaintenance();
  res.json({ success: true, message: result ? "Slot maintenance completed" : "Slot maintenance is already running", result });
});

module.exports = { createCallSlot, getAvailableSlots, getAllSlots, updateCallSlot, deleteCallSlot, maintainSlots, parseSlotTimes, findOverlap };
