const CallSlot = require("../models/CallSlot");
const asyncHandler = require("../middleware/asyncHandler");
const {
  datePattern,
  timePattern,
  formatUtcDate,
  getFutureSlotQuery,
} = require("../utils/slotTime");
const dailySlotStartHour = 16;
const dailySlotEndHour = 23;
const rollingSlotDays = 30;
const autoSlotNote = "Auto-generated daily discovery call slot.";
const ensureCooldownMs = 6 * 60 * 60 * 1000;

let lastEnsureCompletedAt = 0;
let ensureInFlight = null;

const formatHour = (hour) => `${String(hour).padStart(2, "0")}:00`;

const buildDailySlotOperations = () => {
  const startDate = new Date();

  startDate.setUTCHours(0, 0, 0, 0);

  const operations = [];

  for (let dayOffset = 0; dayOffset < rollingSlotDays; dayOffset += 1) {
    const currentDate = new Date(startDate);

    currentDate.setUTCDate(startDate.getUTCDate() + dayOffset);

    const date = formatUtcDate(currentDate);

    for (let hour = dailySlotStartHour; hour < dailySlotEndHour; hour += 1) {
      const startTime = formatHour(hour);
      const endTime = formatHour(hour + 1);

      operations.push({
        updateOne: {
          filter: {
            date,
            startTime,
            endTime,
          },
          update: {
            $setOnInsert: {
              date,
              startTime,
              endTime,
              notes: autoSlotNote,
              isActive: true,
              isBooked: false,
              isAutoGenerated: true,
            },
          },
          upsert: true,
        },
      });
    }
  }

  return operations;
};

const ensureDailyCallSlots = () => {
  const now = Date.now();

  if (
    lastEnsureCompletedAt &&
    now - lastEnsureCompletedAt < ensureCooldownMs
  ) {
    return null;
  }

  if (ensureInFlight) {
    return ensureInFlight;
  }

  ensureInFlight = (async () => {
    const operations = buildDailySlotOperations();

    if (!operations.length) return;

    try {
      await CallSlot.bulkWrite(operations, { ordered: false });
    } catch (error) {
      if (error?.code !== 11000) {
        throw error;
      }
    }

    lastEnsureCompletedAt = Date.now();
  })().finally(() => {
    ensureInFlight = null;
  });

  return ensureInFlight;
};

const findAvailableSlots = () =>
  CallSlot.find({
    ...getFutureSlotQuery(),
    isActive: true,
    isBooked: false,
  }).sort({ date: 1, startTime: 1 });

const isValidDateString = (date) => {
  if (!datePattern.test(date)) return false;

  const parsedDate = new Date(`${date}T00:00:00.000Z`);

  return (
    !Number.isNaN(parsedDate.getTime()) &&
    parsedDate.toISOString().slice(0, 10) === date
  );
};

const validateSlotTime = ({ date, startTime, endTime }) => {
  if (!date || !startTime || !endTime) {
    return "Date, start time, and end time are required";
  }

  if (!isValidDateString(date)) {
    return "Date must be a valid YYYY-MM-DD date";
  }

  if (!timePattern.test(startTime) || !timePattern.test(endTime)) {
    return "Start time and end time must use HH:mm format";
  }

  if (startTime >= endTime) {
    return "End time must be after start time";
  }

  return null;
};

const findDuplicateSlot = ({ date, startTime, endTime, excludeId }) => {
  const query = {
    date,
    startTime,
    endTime,
  };

  if (excludeId) {
    query._id = { $ne: excludeId };
  }

  return CallSlot.findOne(query);
};

const throwDuplicateSlotError = (error, res) => {
  if (error?.code !== 11000) {
    throw error;
  }

  res.status(400);
  throw new Error("A call slot with this exact date and time already exists");
};

// @desc    Create call slot
// @route   POST /api/slots
// @access  Admin
const createCallSlot = asyncHandler(async (req, res) => {
  const { date, startTime, endTime, notes } = req.body || {};

  const validationError = validateSlotTime({ date, startTime, endTime });

  if (validationError) {
    res.status(400);
    throw new Error(validationError);
  }

  const duplicateSlot = await findDuplicateSlot({ date, startTime, endTime });

  if (duplicateSlot) {
    res.status(400);
    throw new Error("A call slot with this exact date and time already exists");
  }

  let slot;

  try {
    slot = await CallSlot.create({
      date,
      startTime,
      endTime,
      notes,
    });
  } catch (error) {
    throwDuplicateSlotError(error, res);
  }

  res.status(201).json({
    success: true,
    message: "Call slot created successfully",
    slot,
  });
});

// @desc    Get public available slots
// @route   GET /api/slots/available
// @access  Public
const getAvailableSlots = asyncHandler(async (req, res) => {
  const ensurePromise = ensureDailyCallSlots();
  const safeEnsurePromise = ensurePromise?.catch((error) => {
    console.error(`Call slot ensure failed: ${error.message}`);
  });
  let slots = await findAvailableSlots();

  if (!slots.length && safeEnsurePromise) {
    await safeEnsurePromise;
    slots = await findAvailableSlots();
  }

  res.json({
    success: true,
    count: slots.length,
    slots,
  });
});

// @desc    Get all slots
// @route   GET /api/slots
// @access  Admin
const getAllSlots = asyncHandler(async (req, res) => {
  const ensurePromise = ensureDailyCallSlots();

  if (ensurePromise) {
    await ensurePromise;
  }

  const slots = await CallSlot.find().sort({ date: 1, startTime: 1 });

  res.json({
    success: true,
    count: slots.length,
    slots,
  });
});

// @desc    Update call slot
// @route   PUT /api/slots/:id
// @access  Admin
const updateCallSlot = asyncHandler(async (req, res) => {
  const { date, startTime, endTime, isActive, isBooked, notes } =
    req.body || {};

  const slot = await CallSlot.findById(req.params.id);

  if (!slot) {
    res.status(404);
    throw new Error("Call slot not found");
  }

  const nextDate = date !== undefined ? date : slot.date;
  const nextStartTime = startTime !== undefined ? startTime : slot.startTime;
  const nextEndTime = endTime !== undefined ? endTime : slot.endTime;

  const validationError = validateSlotTime({
    date: nextDate,
    startTime: nextStartTime,
    endTime: nextEndTime,
  });

  if (validationError) {
    res.status(400);
    throw new Error(validationError);
  }

  const duplicateSlot = await findDuplicateSlot({
    date: nextDate,
    startTime: nextStartTime,
    endTime: nextEndTime,
    excludeId: slot._id,
  });

  if (duplicateSlot) {
    res.status(400);
    throw new Error("A call slot with this exact date and time already exists");
  }

  if (slot.isBooked && isActive === false) {
    res.status(400);
    throw new Error("Cannot disable a booked slot");
  }

  if (isBooked !== undefined && isBooked !== slot.isBooked) {
    res.status(400);
    throw new Error("Slot booking status is managed by appointments");
  }

  if (date !== undefined) slot.date = date;
  if (startTime !== undefined) slot.startTime = startTime;
  if (endTime !== undefined) slot.endTime = endTime;
  if (isActive !== undefined) slot.isActive = isActive;
  if (notes !== undefined) slot.notes = notes;

  let updatedSlot;

  try {
    updatedSlot = await slot.save();
  } catch (error) {
    throwDuplicateSlotError(error, res);
  }

  res.json({
    success: true,
    message: "Call slot updated successfully",
    slot: updatedSlot,
  });
});

// @desc    Delete call slot
// @route   DELETE /api/slots/:id
// @access  Admin
const deleteCallSlot = asyncHandler(async (req, res) => {
  const slot = await CallSlot.findById(req.params.id);

  if (!slot) {
    res.status(404);
    throw new Error("Call slot not found");
  }

  if (slot.isBooked) {
    res.status(400);
    throw new Error("Cannot delete a booked slot");
  }

  if (slot.isAutoGenerated) {
    slot.isActive = false;
    slot.notes = slot.notes
      ? `${slot.notes}\nHidden by admin.`
      : "Auto-generated slot hidden by admin.";

    await slot.save();

    return res.json({
      success: true,
      message: "Auto-generated call slot hidden successfully",
      slot,
    });
  }

  await slot.deleteOne();

  res.json({
    success: true,
    message: "Call slot deleted successfully",
  });
});

module.exports = {
  createCallSlot,
  getAvailableSlots,
  getAllSlots,
  updateCallSlot,
  deleteCallSlot,
};
